### ISSUE TITLE
Jest error with teardown - does not seem to affect functionality, but to be fixed

### ISSUE THREAD

**Issue by priyankapereira1** [rsego-hub/ECE_461#50]
./run test
Testing with jest
Found GITHUB_TOKEN in environment.
Cleared /tmp/jest_rs

> coverage
> jest --coverage --detectOpenHandles

 PASS  tests/top_level.test.ts (6.126 s)
 PASS  tests/urls.test.ts
 PASS  tests/metric.test.ts
 PASS  tests/repository.test.ts
Total: 10
Passed: 10
Running coverage on untested files...
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From tests/top_level.test.ts.

      280 | 		var file_count:NullNum = null;
      281 | 		var line_count:NullNum = null;
    > 282 | 		const eslint = new ESLint({
          | 		               ^
      283 | 			useEslintrc: false,
      284 | 			overrideConfig: {
      285 | 				root: true,

      at getEslintRecommendedConfig (node_modules/eslint/lib/cli-engine/cli-engine.js:618:47)
      at ConfigArrayFactory._loadExtendedBuiltInConfig (node_modules/@eslint/eslintrc/lib/config-array-factory.js:839:50)
      at ConfigArrayFactory._loadExtends (node_modules/@eslint/eslintrc/lib/config-array-factory.js:805:29)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (node_modules/@eslint/eslintrc/lib/config-array-factory.js:749:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (node_modules/@eslint/eslintrc/lib/config-array-factory.js:694:20)
          at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory.create (node_modules/@eslint/eslintrc/lib/config-array-factory.js:489:16)
      at createCLIConfigArray (node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:168:47)
      at CascadingConfigArrayFactory.clearCache (node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:339:32)
      at new ESLint (node_modules/eslint/lib/eslint/eslint.js:449:32)
      at CorrectnessMetric.<anonymous> (src/metric.ts:282:18)
      at src/metric.ts:5082:40
      at Object.<anonymous>.__awaiter (src/metric.ts:5031:10)
      at CorrectnessMetric.get_eslint_on_clone (src/metric.ts:5754:12)
      at CorrectnessMetric.get_eslint_on_clone (src/metric.ts:352:31)
      at fulfilled (src/metric.ts:5045:24)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From tests/top_level.test.ts.

      280 | 		var file_count:NullNum = null;
      281 | 		var line_count:NullNum = null;
    > 282 | 		const eslint = new ESLint({
          | 		               ^
      283 | 			useEslintrc: false,
      284 | 			overrideConfig: {
      285 | 				root: true,

      at ConfigArrayFactory.require [as _loadPlugin] (node_modules/@eslint/eslintrc/lib/config-array-factory.js:1086:42)
      at ConfigArrayFactory._loadExtendedPluginConfig (node_modules/@eslint/eslintrc/lib/config-array-factory.js:887:29)
      at ConfigArrayFactory._loadExtends (node_modules/@eslint/eslintrc/lib/config-array-factory.js:808:29)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (node_modules/@eslint/eslintrc/lib/config-array-factory.js:749:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (node_modules/@eslint/eslintrc/lib/config-array-factory.js:694:20)
          at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory.create (node_modules/@eslint/eslintrc/lib/config-array-factory.js:489:16)
      at createCLIConfigArray (node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:168:47)
      at CascadingConfigArrayFactory.clearCache (node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:339:32)
      at new ESLint (node_modules/eslint/lib/eslint/eslint.js:449:32)
      at CorrectnessMetric.<anonymous> (src/metric.ts:282:18)
      at src/metric.ts:5082:40
      at Object.<anonymous>.__awaiter (src/metric.ts:5031:10)
      at CorrectnessMetric.get_eslint_on_clone (src/metric.ts:5754:12)
      at CorrectnessMetric.get_eslint_on_clone (src/metric.ts:352:31)
      at fulfilled (src/metric.ts:5045:24)

Test Suites: 4 passed, 4 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        15.747 s
Ran all test suites.
Coverage: 23.93%

**Comment by priyankapereira1** [comment]
Redirecting stderr output to coverage/err so it does not affect customer-visible output.

**Comment by priyankapereira1** [comment]
Resolved - was an error with async tests timing out before completion. #60 fixed it.
